export const UPDATE_USER_LIST = "UPDATE_USER_LIST";
export const RESET_USER = "RESET_USER";
export const UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL";
export const UPDATE_USER_HISTORY = "UPDATE_USER_HISTORY";
